config = '''
{
  "signature": 65793,
  "ram_encode": [
    {
      "name": "hevc_videotoolbox",
      "format": "H265",
      "priority": 0,
      "hwdevice": "AV_HWDEVICE_TYPE_NONE"
    }
  ],
  "ram_decode": [
    {
      "name": "h264",
      "format": "H264",
      "priority": 0,
      "hwdevice": "AV_HWDEVICE_TYPE_VIDEOTOOLBOX"
    },
    {
      "name": "hevc",
      "format": "H265",
      "priority": 0,
      "hwdevice": "AV_HWDEVICE_TYPE_VIDEOTOOLBOX"
    },
    {
      "name": "h264",
      "format": "H264",
      "priority": 3,
      "hwdevice": "AV_HWDEVICE_TYPE_NONE"
    },
    {
      "name": "hevc",
      "format": "H265",
      "priority": 3,
      "hwdevice": "AV_HWDEVICE_TYPE_NONE"
    }
  ]
}'''
