#!/usr/bin/env python3
"""Clash Verge Rev 声明式配置注入（幂等，激活期执行，macOS 三台共享）

用法: apply.py <app数据目录> <订阅URL> <混合端口> <自启> <静默启动> <允许局域网> <ipv6> <dns覆写>

管理三件套（文件不存在时按模板补写，App 首启即可读）：
  verge.yaml         App 设置（IVerge）：开机自启 / 静默启动 / 混合端口 / DNS 覆写开关
  clash-verge.yaml   Clash 设置页（IClashTemp）：mixed-port / allow-lan / ipv6
  profiles.yaml      订阅列表（IProfiles）：注入远程订阅并设为 current，下载订阅内容
逐项检查，已符合则跳过；可重复执行。App 运行中不会热重载——部署后需重启 App。
"""
import os
import re
import sys
import time
import urllib.request
import uuid

APP_DIR = os.path.expanduser(sys.argv[1])
SUB_URL = sys.argv[2]
MIXED_PORT = sys.argv[3]
AUTO_LAUNCH = sys.argv[4] == "true"
SILENT_START = sys.argv[5] == "true"
ALLOW_LAN = sys.argv[6] == "true"
IPV6 = sys.argv[7] == "true"
DNS_OVERRIDE = sys.argv[8] == "true"
SUB_NAME = "fan-x"

os.makedirs(APP_DIR, exist_ok=True)


def ensure_scalar(path, pairs, create_lines=None):
    """顶层标量 key 行级收敛：存在则替换，缺失则追加；文件不存在时可选按 create_lines 创建"""
    if not os.path.exists(path):
        if create_lines is None:
            return [], False, "文件不存在，跳过（App 首启生成默认）"
        with open(path, "w", encoding="utf-8") as f:
            f.write("\n".join(create_lines) + "\n")
        return [k for k, _ in pairs], True, os.path.basename(path)
    with open(path, encoding="utf-8") as f:
        text = f.read()
    changed = []
    for key, val in pairs:
        pat = re.compile(rf"^{re.escape(key)}:\s*\S.*$", re.M)
        line = f"{key}: {val}"
        if pat.search(text):
            if pat.sub(line, text, count=1) != text:
                text = pat.sub(line, text, count=1)
                changed.append(key)
        else:
            text = text.rstrip("\n") + "\n" + line + "\n"
            changed.append(key)
    if changed:
        with open(path, "w", encoding="utf-8") as f:
            f.write(text)
    return changed, False, os.path.basename(path)


def report(label, created, changed, ok_note):
    if changed:
        print(f"clash-verge: {label} {'创建' if created else '更新'} {', '.join(changed)}")
    else:
        print(f"clash-verge: {label} {ok_note}")


def ensure_verge():
    create = ["# Clash Verge Config", ""]
    create += [f"{k}: {v}" for k, v in [
        ("enable_auto_launch", str(AUTO_LAUNCH).lower()),
        ("enable_silent_start", str(SILENT_START).lower()),
        ("verge_mixed_port", MIXED_PORT),
        ("enable_dns_settings", str(DNS_OVERRIDE).lower()),
    ]]
    changed, created, label = ensure_scalar(os.path.join(APP_DIR, "verge.yaml"), [
        ("enable_auto_launch", str(AUTO_LAUNCH).lower()),
        ("enable_silent_start", str(SILENT_START).lower()),
        ("verge_mixed_port", MIXED_PORT),
        # enable_dns_settings 本身即"DNS 覆写"开关：true=应用 dns_config.yaml，false=关闭
        ("enable_dns_settings", str(DNS_OVERRIDE).lower()),
    ], create_lines=create)
    report(label, created, changed, "已符合（自启/静默/端口/DNS覆写）")


def ensure_clash_temp():
    path = os.path.join(APP_DIR, "clash-verge.yaml")
    if not os.path.exists(path):
        # App 首启模板（IClashTemp 全字段 Option，缺省走默认；按本机实机导出结构）
        template = f"""# Generated by Clash Verge

mode: rule
mixed-port: {MIXED_PORT}
allow-lan: {str(ALLOW_LAN).lower()}
log-level: info
ipv6: {str(IPV6).lower()}
external-controller: ''
secret: set-your-secret
unified-delay: true
external-controller-cors:
  allow-private-network: true
  allow-origins:
  - tauri://localhost
  - http://tauri.localhost
  - https://yacd.metacubex.one
  - https://metacubex.github.io
  - https://board.zash.run.place
tun:
  enable: false
  stack: gvisor
  auto-route: true
  strict-route: false
  auto-detect-interface: true
  dns-hijack:
  - any:53
external-controller-unix: /tmp/verge/verge-mihomo.sock
proxies: []
proxy-groups: []
rules: []
"""
        with open(path, "w", encoding="utf-8") as f:
            f.write(template)
        print("clash-verge: clash-verge.yaml 不存在，已按模板创建")
        return
    changed, created, label = ensure_scalar(path, [
        ("mixed-port", MIXED_PORT),
        ("allow-lan", str(ALLOW_LAN).lower()),
        ("ipv6", str(IPV6).lower()),
    ])
    report(label, created, changed, "已符合（端口/局域网/IPv6）")


def ensure_subscription():
    path = os.path.join(APP_DIR, "profiles.yaml")
    # 确定性 uid（uuid5(url)）：幂等注入不重复；file 名 = uid.yaml
    uid = uuid.uuid5(uuid.NAMESPACE_URL, SUB_URL).hex[:22]
    sub_file = uid + ".yaml"
    msgs = []

    if not os.path.exists(path):
        text = ("# Profiles Config for Clash Verge\n\n"
                "current: null\n\nitems:\n")
        mode = "create"
    else:
        with open(path, encoding="utf-8") as f:
            text = f.read()
        mode = "patch"

    has_sub = re.search(rf"^\s*url:\s*{re.escape(SUB_URL)}\s*$", text, re.M) is not None
    if has_sub:
        if not re.search(rf"^current:\s*{re.escape(uid)}\s*$", text, re.M):
            text = re.sub(r"^current:.*$", f"current: {uid}", text, count=1, flags=re.M)
            with open(path, "w", encoding="utf-8") as f:
                f.write(text)
            msgs.append("订阅已存在，current 已指向")
        else:
            msgs.append("订阅已存在且为 current")
    else:
        item = "\n".join([
            f"- uid: {uid}",
            "  type: remote",
            f"  name: {SUB_NAME}",
            f"  file: {sub_file}",
            f"  url: {SUB_URL}",
            f"  updated: {int(time.time())}",
        ])
        m = re.search(r"^items:\s*$", text, re.M)
        if m is None:
            # 异常结构：追加 items 段（保留原内容）
            text = text.rstrip("\n") + "\n\nitems:\n"
            m = re.search(r"^items:\s*$", text, re.M)
        text = text[:m.end()] + "\n" + item + text[m.end():]
        if not re.search(r"^current:", text, re.M):
            text = text.rstrip("\n") + "\ncurrent: " + uid + "\n"
        else:
            text = re.sub(r"^current:.*$", f"current: {uid}", text, count=1, flags=re.M)
        with open(path, "w", encoding="utf-8") as f:
            f.write(text)
        msgs.append(f"注入订阅 {SUB_NAME}（{mode}，current 已指向）")

    # 订阅内容下载（失败仅警告：App 内可手动更新；App 读不到文件时也会自行拉取）
    profiles_dir = os.path.join(APP_DIR, "profiles")
    os.makedirs(profiles_dir, exist_ok=True)
    dl = os.path.join(profiles_dir, sub_file)
    if not os.path.exists(dl):
        try:
            req = urllib.request.Request(
                SUB_URL, headers={"User-Agent": "clash-verge-rev/2.5.2"})
            with urllib.request.urlopen(req, timeout=20) as r:
                data = r.read()
            with open(dl, "wb") as f:
                f.write(data)
            msgs.append(f"订阅内容已下载（{len(data)}B）")
        except Exception as e:  # noqa: BLE001 —— 网络失败不阻断部署
            print(f"警告: 订阅内容下载失败（App 内手动更新即可）：{e}")
    print("clash-verge: " + "；".join(msgs))


if __name__ == "__main__":
    ensure_verge()
    ensure_clash_temp()
    ensure_subscription()
